### ISSUE TITLE
Hello author, I have a question for you about the YFCC100M dataset

### ISSUE THREAD

**Issue by MnYangs** [xinliu29/NCMNet#1]
The link you provided to download the raw_data_yfcc.tar.gz file is not working. The reason should be that altizure platform is closed. Do you have any other downloading methods?

I look forward to your reply. Thank you.

**Comment by xinliu29** [comment]
Sorry, the YFCC100M data is derived from OANet. You can contact the author of OANet.

**Comment by MnYangs** [comment]
Ok, I see. Thank you for your response.
