### ISSUE TITLE
Inference with 2 images

### ISSUE THREAD

**Issue by Vincentqyw** [xinliu29/NCMNet#3]
Great work! I just wondering how to inference with 2 images. Are there any examples, thanks.

**Comment by xinliu29** [comment]
Thank you for your attention. For given two images, you can use existing feature methods (such as SIFT or SuperPoint) to estimate the initial correspondences, and then utilize our model for correspondence pruning. We will publish a demo about this in the future.

**Comment by Vincentqyw** [comment]
Thanks.

**Comment by Vincentqyw** [comment]
I found another project with a simple inference demo, maybe we can use these codes as a reference. Here is the code: https://github.com/SuhZhang/ConvMatch/blob/master/demo/demo.py#L66-L111

**Comment by xinliu29** [comment]
Yes. This can be used for inference.

**Comment by xinliu29** [comment]
The demo has been open sourced, thank you for your interest.
